import React, { useState } from 'react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { api } from '../api';
const format = (n,currency='INR') => new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:0}).format(n||0);
export function InvestmentCalculator({ title='Investment calculator' }) {
 const [type,setType]=useState('lumpsum'), [currency,setCurrency]=useState('INR'), [form,setForm]=useState({investment:'100000',annual_return:'10',years:'5'}), [result,setResult]=useState(null), [error,setError]=useState(''), [loading,setLoading]=useState(false);
 async function calculate(e){e.preventDefault();setError('');setLoading(true);try{const body=type==='sip'?{monthly_investment:Number(form.investment),annual_return:Number(form.annual_return),years:Number(form.years)}:{investment:Number(form.investment),annual_return:Number(form.annual_return),years:Number(form.years)};setResult(await api('/api/calculator/'+type,{method:'POST',body:JSON.stringify(body)}));}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <section className="calculator"><div className="panel-head"><div><h2>{title}</h2><p>Hypothetical growth based on your assumed annual return.</p></div><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>INR</option><option>USD</option></select></div><div className="tabs"><button className={type==='lumpsum'?'active':''} onClick={()=>setType('lumpsum')}>Lumpsum</button><button className={type==='sip'?'active':''} onClick={()=>setType('sip')}>SIP</button></div><form className="calc-form" onSubmit={calculate}><label>{type==='sip'?'Monthly Investment':'Investment Amount'}<input type="number" min="1" required value={form.investment} onChange={e=>setForm({...form,investment:e.target.value})}/></label><label>Expected Annual Return (%)<input type="number" min="-99.99" max="1000" step="0.01" required value={form.annual_return} onChange={e=>setForm({...form,annual_return:e.target.value})}/></label><label>Investment Period (years)<input type="number" min="1" max="100" step={type==='sip'?'1':'0.5'} required value={form.years} onChange={e=>setForm({...form,years:e.target.value})}/></label><button disabled={loading}>{loading?'Calculating…':'Calculate estimate'}</button></form>{error&&<div className="error">{error}</div>}{result&&<><div className="result-grid"><Metric label="Total invested" value={format(result.total_invested,currency)}/><Metric label="Estimated value" value={format(result.estimated_value,currency)}/><Metric label="Estimated gain" value={format(result.estimated_gain,currency)}/></div><div className="chart-box"><ResponsiveContainer width="100%" height={260}><LineChart data={result.yearly_values}><XAxis dataKey="year" tickFormatter={x=>x===0?'Start':`Year ${x}`}/><YAxis tickFormatter={x=>format(x,currency)}/><Tooltip formatter={v=>format(v,currency)} labelFormatter={x=>x===0?'Start':`Year ${x}`}/><Legend/><Line type="monotone" dataKey="invested" stroke="#8b96ad" name="Invested"/><Line type="monotone" dataKey="value" stroke="#5eead4" strokeWidth={3} name="Estimated value"/></LineChart></ResponsiveContainer></div></>}<p className="disclaimer">Investment calculator results are hypothetical estimates based on the assumed return entered by you. Actual cryptocurrency returns can be substantially different.</p></section>;
}
function Metric({label,value}){return <article className="metric"><span>{label}</span><b>{value}</b></article>}
export default function Calculator(){return <div className="page narrow"><InvestmentCalculator /></div>}
