import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';

const money = n => n == null ? '—' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?6:2}).format(n);
const pct = n => n == null ? '—' : `${n>=0?'+':''}${Number(n).toFixed(2)}%`;
function Metric({label,value}) { return <article className="metric"><span>{label}</span><b>{value}</b></article>; }

export default function Dashboard() {
 const [coins,setCoins]=useState([]), [search,setSearch]=useState(''), [results,setResults]=useState([]), [sort,setSort]=useState('cap'), [signalFilter,setSignalFilter]=useState('all'), [error,setError]=useState(''), [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setCoins(await api('/api/watchlist'));}catch(e){setError(e.message)}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 useEffect(()=>{const timer=setTimeout(async()=>{if(!search.trim())return setResults([]);try{setResults(await api('/api/crypto/search?q='+encodeURIComponent(search)))}catch(e){setError(e.message)}},350);return()=>clearTimeout(timer)},[search]);
 const add=async c=>{try{await api('/api/watchlist',{method:'POST',body:JSON.stringify({coin_id:c.id,name:c.name,symbol:c.symbol})});setSearch('');setResults([]);load()}catch(e){setError(e.message)}};
 const remove=async id=>{try{await api('/api/watchlist/'+id,{method:'DELETE'});load()}catch(e){setError(e.message)}};
 const screened=useMemo(()=>[...coins].filter(c=>signalFilter==='all'||c.direction?.toLowerCase()===signalFilter).sort((a,b)=>{const change=x=>x.price_change_percentage_24h||0,predicted=x=>x.predicted_change_percent||0;if(sort==='gain')return change(b)-change(a);if(sort==='loss')return change(a)-change(b);if(sort==='volume')return (b.total_volume||0)-(a.total_volume||0);if(sort==='predictedgain')return predicted(b)-predicted(a);if(sort==='predictedloss')return predicted(a)-predicted(b);return (b.market_cap||0)-(a.market_cap||0)}),[coins,sort,signalFilter]);
 const average=items=>items.length?items.reduce((sum,item)=>sum+(item||0),0)/items.length:0;
 return <div className="page"><section className="hero"><div><p className="eyebrow">PERSONAL MARKET DASHBOARD</p><h1>My Watchlist</h1><p>Track market context and statistical next-day estimates in one calm place.</p></div><div className="search-wrap"><input placeholder="Search cryptocurrency…" value={search} onChange={e=>setSearch(e.target.value)}/>{results.length>0&&<div className="search-results">{results.map(c=><button key={c.id} onClick={()=>add(c)}>{c.image&&<img src={c.image}/>}<span>{c.name}<small>{c.symbol.toUpperCase()}</small></span><b>+ Add</b></button>)}</div>}</div></section>
 {error&&<div className="error">{error}</div>}<section className="summary-grid"><Metric label="Total Coins" value={coins.length}/><Metric label="Bullish" value={coins.filter(x=>x.direction==='Bullish').length}/><Metric label="Neutral" value={coins.filter(x=>x.direction==='Neutral').length}/><Metric label="Bearish" value={coins.filter(x=>x.direction==='Bearish').length}/><Metric label="Average 24h Change" value={pct(average(coins.map(x=>x.price_change_percentage_24h)))}/></section>
 <section className="panel"><div className="panel-head"><div><h2>Watchlist</h2><p>Current daily prices come from Alpha Vantage.</p></div></div>{loading?<p className="empty">Loading your market data…</p>:coins.length===0?<p className="empty">Search above to add your first cryptocurrency.</p>:<div className="coin-grid">{coins.map(c=><article className="coin-card" key={c.id}><div className="coin-name">{c.image&&<img src={c.image}/>}<div><h3>{c.name}</h3><span>{c.symbol?.toUpperCase()}</span></div></div>{c.market_error?<p className="muted">{c.market_error}</p>:<><strong>{money(c.current_price)}</strong><div className={c.price_change_percentage_24h>=0?'positive':'negative'}>24h {pct(c.price_change_percentage_24h)}</div><dl><div><dt>Market cap</dt><dd>{money(c.market_cap)}</dd></div><div><dt>Volume</dt><dd>{money(c.total_volume)}</dd></div></dl></>}<div className="card-actions"><Link className="secondary" to={'/crypto/'+c.id}>View</Link><button className="danger" onClick={()=>remove(c.id)}>Remove</button></div></article>)}</div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Watchlist screener</h2><p>Sort and filter your tracked assets.</p></div><div style={{display:'flex',gap:'10px'}}><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="cap">Highest market cap</option><option value="gain">Highest 24h gain</option><option value="loss">Largest 24h loss</option><option value="volume">Highest volume</option><option value="predictedgain">Highest predicted gain</option><option value="predictedloss">Largest predicted loss</option></select></label><label>Filter<select value={signalFilter} onChange={e=>setSignalFilter(e.target.value)}><option value="all">All signals</option><option value="bullish">Bullish</option><option value="neutral">Neutral</option><option value="bearish">Bearish</option></select></label></div></div><div className="table-wrap"><table><thead><tr><th>Coin</th><th>Price</th><th>24h</th><th>Predicted</th><th>Signal</th><th>Market cap</th></tr></thead><tbody>{screened.map(c=><tr key={c.id}><td><Link to={'/crypto/'+c.id}>{c.symbol?.toUpperCase()} <span className="muted">{c.name}</span></Link></td><td>{money(c.current_price)}</td><td className={c.price_change_percentage_24h>=0?'positive':'negative'}>{pct(c.price_change_percentage_24h)}</td><td className={(c.predicted_change_percent||0)>=0?'positive':'negative'}>{pct(c.predicted_change_percent)}</td><td>{c.direction||'—'}</td><td>{money(c.market_cap)}</td></tr>)}</tbody></table></div></section>
 </div>;
}
